### ISSUE TITLE
Bug Report: Thiếu tên môn học ở chart "Điểm các môn"

### ISSUE THREAD

**Issue by TranHuy2k2** [thangved/ctu-extension#107]
**Describe the bug**
Ở chart điểm các môn, ở trục tung (chứa tên các môn) bị thiếu một vài môn. Mặc dù có cột điểm của môn đó nhưng không có tên môn.

**To Reproduce**
1. Bật CTU Extension
2. Đăng nhập vào htql
3. Ở chart "Điểm các môn" bị thiếu tên môn.

**Expected behavior**
Ở chart cần hiển thị đầy đủ các tên môn.

**Screenshots**
Ở học kì cuối thiếu điểm môn "Mạng máy tính" và không có nhãn "Nguyên lý máy học" ở trục tung.
![Screenshot from 2023-12-15 19-48-05](https://github.com/thangved/ctu-extension/assets/86108622/43d17434-17a5-4ac3-8958-9af6003edae7)

**Additional context**
Danh sách các môn học của mình kỳ này:
- Nguyên lý máy học
- Mạng máy tính
- An toàn và Bảo mật thông tin
- Niên luận ngành KHMT
- Học sâu
- Quản trị hệ thống

**Comment by thangved** [comment]
Cảm ơn bạn đã báo cáo. Nếu được thì bạn giúp mình fix lỗi này luôn nhé 🐧

**Comment by TranHuy2k2** [comment]
Bug report tự assign bạn lun ròi, nên bạn làm lun nhé 🐧🐧

**Comment by thangved** [comment]
Đã fix nhóe @TranHuy2k2
